import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Slide } from 'react-slideshow-image';
import 'react-slideshow-image/dist/styles.css'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

function Slideshow() {
    return (
        <div className="slide-container">
            <Slide>
                {slideImages.map((slideImage, index) => (
                    <div key={index}>
                        <div style={{ ...divStyle, 'backgroundImage': `url(${slideImage.url})` }}>

                        </div>
                    </div>
                ))}
            </Slide>
        </div>
    )
}

const spanStyle = {
    background: '#efefef',
    color: '#000000'
}

const divStyle = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundSize: 'cover',
    minWidth: "500px",
    minHeight: '50vh',
    width: "auto",
    height: "90vh",
}

const slideImages = [
    {
        url: '/1.jpg',
        caption: 'Slide 1'
    },
    {
        url: '/2.jpg',
        caption: 'Slide 2'
    },
    {
        url: '/3.jpg',
        caption: 'Slide 3'
    },

    {
        url: '/4.jpg',
        caption: 'Slide 4'
    },

    {
        url: '/5.jpg',
        caption: 'Slide 5'
    },
];

export default function Full() {
    return (
        <>
            <Head>
                <title>PeterHof Palace</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <h1 className={`${styles.title}`}>PeterHof Palace</h1>
                <hr className={`${styles.hr}`} />
                <div className={`${styles.asd}`} style={{
                    width: "100%",
                    justifyContent: 'center',
                    justifyItems: 'center',
                    alignItems: 'center',
                }}>
                    <div style={{
                        minWidth: "40vw",
                        minHeight: "800px",
                        width: "80%",
                        height: "80vh",
                        margin: 0,
                        padding: 0,
                    }}>
                        <Slideshow />
                    </div>
                </div>

            </main>
        </>
    )
}

