import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Slide } from 'react-slideshow-image';
import 'react-slideshow-image/dist/styles.css'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

function Slideshow() {
  return (
    <div className="slide-container">
      <Slide>
        {slideImages.map((slideImage, index) => (
          <div key={index}>
            <div style={{ ...divStyle, 'backgroundImage': `url(${slideImage.url})` }}>

            </div>
          </div>
        ))}
      </Slide>
    </div>
  )
}

const divStyle = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundSize: 'cover',
  minWidth: "500px",
  minHeight: '50vh',
  width: "auto",
  height: "fit-content",
}

const slideImages = [
  {
    url: '/1.jpg',
    caption: 'Slide 1'
  },
  {
    url: '/2.jpg',
    caption: 'Slide 2'
  },
  {
    url: '/3.jpg',
    caption: 'Slide 3'
  },

  {
    url: '/4.jpg',
    caption: 'Slide 4'
  },

  {
    url: '/5.jpg',
    caption: 'Slide 5'
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>PeterHof Palace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={`${styles.title}`}>PeterHof Palace</h1>
        <hr className={`${styles.hr}`} />
        <div className={`${styles.asd}`}>
          <div style={{
            minWidth: "40vw",
            minHeight: "800px",
            width: "40vw",
            height: "20vh",
          }}>
            <Slideshow />
          </div>
          <p className={`${styles.yazi}`} >

            <p className={`${styles.span}`} style={{ fontWeight: 'bold' }}>
              Interesting Facts about Peterhof Palace
            </p>

            <p className={`${styles.span}`}>
              1- The palace was built by being influenced by the Palace of Versailles in France.
            </p>
            <p className={`${styles.span}`}>
              2- Peter the Great had this palace built after winning a victory against the Swedes.
            </p>
            <p className={`${styles.span}`}>
              3- Just visiting the gardens of Peterhof Palace will take half a day.
            </p>

            <p className={`${styles.span}`}>
              4- It was built by the Russian Tsar Peter on the coast of the Baltic Sea.
            </p>

            <p className={`${styles.span}`}>
              5- The palace, which was occupied by the Germans during World War II, was used as a German headquarters for 4 years and then bombed by them.
            </p>

          </p>
        </div>

      </main>
    </>
  )
}

