import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Slide } from 'react-slideshow-image';

import SlideImages from './slideImages.json'

import 'react-slideshow-image/dist/styles.css'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
const slideImages = SlideImages.slideImages;

function Slideshow() {
  return (
    <div className="slide-container">
      <Slide>
        {slideImages.map((slideImage, index) => (
          <div key={index}>
            <div style={{ ...divStyle, 'backgroundImage': `url(${slideImage.url})` }}>

            </div>
          </div>
        ))}
      </Slide>
    </div>
  )
}

const divStyle = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundSize: 'cover',
  minWidth: "500px",
  minHeight: '50vh',
  width: "auto",
  height: "fit-content",
}

function Yazi({ children }) {
  return <>
    <p className={`${styles.span}`}>
      {children}
    </p>
  </>
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Peterhof Palace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={`${styles.title}`}>Peterhof Palace</h1>
        <hr className={`${styles.hr}`} />
        <div className={`${styles.asd}`}>
          <div style={{
            minWidth: "40vw",
            minHeight: "800px",
            width: "40vw",
            height: "20vh",
          }}>
            <Slideshow />
          </div>
          <div className={`${styles.yazi}`} >

            <p className={`${styles.span}`} style={{ fontWeight: 'bold' }}>
              Interesting Facts about Peterhof Palace
            </p>

            {[
              "The palace was built by being influenced by the Palace of Versailles in France.",
              "Peter the Great had this palace built after winning a victory against the Swedes.",
              "Just visiting the gardens of Peterhof Palace will take half a day.",
              "It was built by the Russian Tsar Peter on the coast of the Baltic Sea.",
              "The palace, which was occupied by the Germans during World War II, was used as a German headquarters for 4 years and then bombed by them.",
              `In Dutch "Pieterhof", means "Pieter's Court" so its name comes from here.`,
              `There is a Statue of Poseidon near the Palace.`,

            ].map((fact, index) => {
              return <Yazi key={index}>{index + 1}- {fact}</Yazi>

            })}

          </div>
        </div>

      </main>
    </>
  )
}

